# Generated by Django 3.0 on 2020-07-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_handle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='question',
        ),
    ]
