# Generated by Django 3.0 on 2020-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_handle', '0006_auto_20200710_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='question_a',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='question_b',
            new_name='question_A',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='question_c',
            new_name='question_B',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='question_d',
            new_name='question_C',
        ),
        migrations.AddField(
            model_name='post',
            name='question_D',
            field=models.CharField(default='', max_length=100),
        ),
    ]
